import { z } from "zod";

export const AnimeSchema = z.object({
  id: z.number().int().nullable(),
  airedFrom: z.date().nullable(),
  airedTo: z.date().nullable(),
  airing: z.boolean().nullable(),
  approved: z.boolean().nullable(),
  background: z.string().nullable(),
  broadcastDay: z.string().nullable(),
  broadcastTime: z.string().nullable(),
  broadcastTimezone: z.string().nullable(),
  broadcastString: z.string().nullable(),
  demographics: z.array(z.string()).nullable(),
  duration: z.string().nullable(),
  episodes: z.number().int().nullable(),
  explicitGenres: z.array(z.string()).nullable(),
  favorites: z.number().int().nullable(),
  genres: z.array(z.string()).nullable(),
  imageJpg: z.string().nullable(),
  imageWebp: z.string().nullable(),
  licensors: z.array(z.string()).nullable(),
  malId: z.number().int(),
  members: z.number().int().nullable(),
  popularity: z.number().int().nullable(),
  producers: z.array(z.string()).nullable(),
  rank: z.number().int().nullable(),
  rating: z.string().nullable(),
  score: z.number().nullable(),
  scoredBy: z.number().int().nullable(),
  season: z.string().nullable(),
  source: z.string().nullable(),
  status: z.string().nullable(),
  studios: z.array(z.string()).nullable(),
  synopsis: z.string().nullable(),
  themes: z.array(z.string()).nullable(),
  title: z.string().nullable(),
  titleEnglish: z.string().nullable(),
  titleJapanese: z.string().nullable(),
  titleSynonyms: z.array(z.string()).nullable(),
  trailerYoutubeId: z.string().nullable(),
  trailerUrl: z.string().nullable(),
  trailerEmbedUrl: z.string().nullable(),
  type: z.string().nullable(),
  url: z.string().nullable(),
  year: z.number().int().nullable()
})
